#!/bin/bash


sudo add-apt-repository universe
# kivy
sudo add-apt-repository -y ppa:kivy-team/kivy
sudo add-apt-repository -y ppa:thopiekar/pygame

sudo apt-get update
sudo apt-get install -y python-pip
sudo apt-get install -y python-kivy

pip install .

sudo python run.py
